- name: 'bug'
  color: 'C73E1D'
  description: 'Something is not working'
- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'
- name: 'duplicate'
  color: 'cfd3d7'
  description: 'This issue or pull request already exists'
- name: 'enhancement'
  color: 'a2eeef'
  description: 'New feature or request'
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'
- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'
- name: 'invalid'
  color: 'e4e669'
  description: 'This does not seem right'
- name: 'question'
  color: 'd876e3'
  description: 'Further information is requested'
- name: 'wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'
- name: 'accepted'
  color: '57F80A'
  description: 'This idea or request accepted'
- name: 'rejected'
  color: 'FE3B00'
  description: 'This idea or request rejected'
- name: 'semver:patch'
  color: '79490E'
  description: 'Version: Patch'
- name: 'semver:minor'
  color: '79490E'
  description: 'Version: Minor'
- name: 'semver:major'
  color: '79490E'
  description: 'Version: Major'
- name: 'idea'
  color: '059D9D'
  description: 'Idea'
- name: 'to-do'
  color: '0A0E45'
  description: 'To-Do'
- name: 'in-progress'
  color: '560443'
  description: 'In progress'
- name: 'testing'
  color: 'A8C247'
  description: 'Testing'
- name: 'done'
  color: '019D4D'
  description: 'Done'
- name: 'rewrite'
  color: 'D8EFBA'
  description: 'Need to be rewrite'
- name: 'refactor'
  color: '8BB2A9'
  description: 'Need to be refactor'
- name: 'need-more-info'
  color: '80c042'
  description: ''
- name: 'packages:cleaner'
  color: '3E0171'
  description: ''
- name: 'packages:bot'
  color: '3E0171'
  description: ''
- name: 'packages:engine'
  color: '3E0171'
  description: ''
- name: 'packages:database'
  color: '3E0171'
  description: ''
