blank_issues_enabled: true
contact_links:
  - name: 🤔 Uzun soru veya fikirler?
    url: https://github.com/Fire-Oceann/fireocean-s/discussions
    about: Uzun biçimli sorular sorun ve fikirleri tartışın.
  - name: 💬 Discord Topluluk Sohbeti
    url: https://discord.gg/eqUGZa8A
    about: Hızlı sorular sorun veya `Fire Ocean - TR Source` topluluğu Discord sunucusunda sohbet edin.
