name: "📚 Dokümantasyon"
description: Belgelerle ilgili bir sorunu bildirin
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Bu şablon, aşağıdakiler de dahil olmak üzere, kesinlikle belge talepleri için kullanılır:

        - Belgelenmemiş API'lerin belgelenmesi;
        - Belirli bir konu üzerinde detaylandırma;
        - Harici linklerin güncellenmesi;
        - kod tabanının kendisine dokunmayı gerektirmeyen herhangi bir şey.

        Belgeleri izlediyseniz ancak işler yolunda gitmiyorsa, hatalı olanın belge mi yoksa kod mu olduğunu düşünmek için biraz zaman ayırın. İkincisinde, "hata" şablonunu kullanmayı tercih edin.

        Birleştirilmemiş belge çekme isteklerini nadiren kapatırız. Belge talebiniz ise:

        - Docusaurus kullanıcılarının önemli bir kısmı ile ilgili;
        - Harici araçlarla ilgili değil (örneğin, dağıtım iş akışı. Bir "dağıtım" bölümümüz var ama bunu çoğunlukla olduğu gibi tutmaya karar verdik);
        - Başka bir yerde belgelenmemiş (veya belgelenmişse, söz konusu çok keşfedilemez yerlerde).

        Bu sorunu bildirmeden doğrudan bir çekme isteği göndermeye devam edebilirsiniz ve çalışmanızı iyileştirebiliriz.
        Yukarıdaki gereksinimlerin bazılarının karşılanmadığını düşünüyorsanız veya kendiniz katkıda bulunamıyorsanız, sorun yine de memnuniyetle karşılanır.

  - type: checkboxes
    attributes:
      label: Sorunlarla ilgili Katkıda Bulunan Yönergeleri okudunuz mu?
      options:
        - label: [Sorunlarla ilgili Katkıda Bulunan Yönergeleri](https://github.com) okudum.
          required: true

  - type: textarea
    attributes:
      label: Açıklama
      description: Sorunun ne olduğuna dair net ve özlü bir açıklama.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        Bu soruna katkıda bulunabileceğinizi düşünüyorsanız, lütfen aşağıdaki kutuyu işaretleyin. Bu bize ve katkı arayan diğer kişilere birinin üzerinde çalıştığını söyler.
         Bu kutuyu işaretlerseniz, lütfen 7 gün içinde bir çekme isteği gönderin, böylece bunu başka birine devredebiliriz.
      options:
        - label: Bu belge talebini kendim ele almaya hazırım.
