name: "Greet With A Random Joke"
on:
  issues:
    types: [opened, reopened]
jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: mast joke mara
        uses: deep5050/MastJokeMara@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue_msg: |
            Merhaba, {{author}},
            Bir konu açtığınız için teşekkürler :blue_heart: Sorununuz yakında bakımcılar tarafından görülecektir.
            Katkıda bulunanlar :people_holding_hands:  sizin gibi açık kaynak topluluğunu :earth_africa:  öğrenmek :book: , ilham vermek :angel:, ve :art: oluşturmak için harika bir yer haline getiriyor.
             Araştıracağız :eyes:  ve en kısa sürede size geri döneceğiz :+1: . 
             Bize yeterli bilgiyi verdiğinizden emin olun :information_source:.
             O zamana kadar bu şakanın tadını çıkarın :point_down: , umarım beğenirsiniz :smile:
            
            {{joke}}
